- name: FDSE SOAR Installer
  hosts: all
  vars_files:
    - vars.yaml
  tasks:    
    - name: Disabling SELinux state
      become: yes
      become_user: root
      selinux:
        state: disabled

    - name: Reboot
      tags: reboot
      become: yes
      become_user: root
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: Wait 300 seconds, but only start checking after 20 seconds
      ansible.builtin.wait_for_connection:
        delay: 20
        timeout: 300

    - name: Install yum packages
      become: yes
      become_user: root
      ansible.builtin.yum:
        name:
          - ntpdate
          - libevent
          - libicu
          - c-ares
          - bind-utils
          - java-1.8.0-openjdk-headless
          - mailcap
          - fontconfig
          - ntpdate
          - perl
          - rsync
          - xmlsec1
          - xmlsec1-openssl
          - libxslt
          - ntp
          - zip
          - net-tools
          - policycoreutils-python
          - libxml2
          - libcurl
          - gnutls
          - openssl-devel
          - libffi-devel
          - bzip2-devel
          - "@Development tools"
        state: latest

    - name: Create Unprivileged user for SOAR
      become: yes
      become_user: root
      ansible.builtin.user:
        name: soaruser
        comment: Splunk SOAR user
        password: "{{ vars.soaruser_password | password_hash('sha512') }}"
        create_home: true

    - name: Add soaruser to group wheel
      become: yes
      become_user: root
      ansible.builtin.user:
        name: soaruser
        groups: wheel
        append: yes

    - name: Create phantom limits file
      become: yes
      become_user: root
      copy:
        src: ./25-phantom-limits.conf
        dest: /etc/security/limits.d/25-phantom-limits.conf      

    - name: Create SOAR installation folder
      become: yes
      become_user: root
      ansible.builtin.file:
        path: /opt/soar
        state: directory
        owner: soaruser
        mode: '0755'

    - name: check openssl existence
      become: yes
      become_user: soaruser
      shell: "openssl version"
      changed_when: false
      failed_when: false
      register: openssl_exist

    - name: Install openssl11 packages
      become: yes
      become_user: root
      ansible.builtin.yum:
        name: openssl11
        state: latest
      when: openssl_exist.rc != 0
    
    - name: Openssl which
      become: yes
      become_user: root
      shell: "which openssl11"
      register: openssl11_path
      when: openssl_exist.rc != 0
    
    - name: Set env dir for openss11 as openssl
      become: yes
      become_user: root
      shell: "mv {{openssl11_path.stdout}} /usr/bin/openssl"
      when: openssl_exist.rc != 0

    - name: Apply the new Security Settings
      become: yes
      become_user: root
      shell: "sysctl --system"  
      register: patchresult
    
    - name: Check for Python
      shell: python3 --version
      changed_when: false
      failed_when: false
      register: check_python
    
    - name: Install python and pip3
      become: yes
      become_user: root
      ansible.builtin.yum:
        name:
          - python36
        state: present
      when: check_python.rc != 0
    
    - name: Upgrade pip, setuptools and wheel
      become: yes
      become_user: root
      shell: python3 -m pip install --upgrade pip setuptools wheel
      when: check_python.rc != 0
    
    - name: Install python passlib module
      become: yes
      become_user: root
      ansible.builtin.pip:
        name: passlib
        executable: pip3
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Download phantom tar package
      become: yes
      become_user: soaruser
      ansible.builtin.get_url:
        url: '{{ vars.soar_download_url }}'
        dest: /tmp/phantom.tar

    - name: extract phantom tar package
      become: yes
      become_user: soaruser
      ansible.builtin.unarchive:
        remote_src: true
        src: /tmp/phantom.tar
        dest: /tmp/

    - name: Run installer SOAR < 5.3v
      become: yes
      become_user: soaruser
      shell: "/tmp/phantom_tar_install.sh install --https-port=8443"
      when: 
        - vars.soar_version < 5.3
    
    - name: Run installer SOAR >= 5.3v
      become: yes
      become_user: soaruser
      shell:  "/tmp/splunk-soar/soar-install --splunk-soar-home /opt/soar/ --ignore-warnings -y"
      when: 
        - vars.soar_version >= 5.3
